apiVersion: v1
kind: Service
metadata:
  name: indfood-imgclassification
spec:
  type: NodePort
  selector:
    app: indfood-imgclassification # link name
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9696
    nodePort: 30080